##asking user to fill their biodata
name=input('enter your name')
print('NAME','=',name)
dob=input('enter your dob')
print('DOB','=',dob)
f=input('enter your father name')
print('FATHER NAME','=',f)
m=input('enter your mother name')
print('MOTHER NAME','=',m)
t=input('enter your mother tounge')
print('MOTHER TOUNGE','=',t)
p=input('enter your phone number')
print('PHONE NUMBER','=',p)
##adding to integers
a=input('enter an even prinme composite number')
b=input('enter a number which is 10<8')
a=int(a)
b=int(b)
print('a','+','b','=',a+b)
print('a','-','b','=',a-b)
print('a','*','b','=',a*b)
print('a','/','b','=',a/b)
print('a','%','b','=',a%b)
print('a','//','b','=',a//b)
